#
###################################
# Site wide configuration
####################################
#
title: Infinity Code
email: lech@infinitycode.io
description: Teach What You Learn. My journey to becoming a successful Web Developer
url: https://infinitycodepl.github.io/blog/ # the base hostname & protocol for your site
keywords: ["Personal blog", "Web Developer", "coding"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Warsaw
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:categories/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Infinity Code
  avatar: 
  job: "Teach what you learn"
  bio: "My journey to becoming a successful Web Developer"
  email: lech@infinitycode.io
  disqus-shortname: infinity-code
  twitter: lechrudnicki #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: infinitycodePL #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: lech-rudnicki #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username